name: snews-data-formats-CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version:
            -3.9
            -3.10
            -3.11
            -3.12

      - name: Install dependencies
        run: |
          sudo apt update --yes && sudo apt install --yes git build-essential graphviz
          pip install poetry
          poetry install

      - name: Test
        run: poetry run pytest
